# Form implementation generated from reading ui file 'addWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(370, 193)
        self.widget = QtWidgets.QWidget(parent=AddWindow)
        self.widget.setGeometry(QtCore.QRect(190, 150, 168, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addBtn = QtWidgets.QPushButton(parent=self.widget)
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout_5.addWidget(self.addBtn)
        self.cancelBtn = QtWidgets.QPushButton(parent=self.widget)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_5.addWidget(self.cancelBtn)
        self.widget1 = QtWidgets.QWidget(parent=AddWindow)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 343, 136))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.number = QtWidgets.QLineEdit(parent=self.widget1)
        self.number.setObjectName("number")
        self.horizontalLayout.addWidget(self.number)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.phone = QtWidgets.QLineEdit(parent=self.widget1)
        self.phone.setObjectName("phone")
        self.horizontalLayout_2.addWidget(self.phone)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.name = QtWidgets.QLineEdit(parent=self.widget1)
        self.name.setObjectName("name")
        self.horizontalLayout_3.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.widget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.flat = QtWidgets.QLineEdit(parent=self.widget1)
        self.flat.setObjectName("flat")
        self.horizontalLayout_4.addWidget(self.flat)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(AddWindow)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)

    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "Добавить"))
        self.addBtn.setText(_translate("AddWindow", "Добавить"))
        self.cancelBtn.setText(_translate("AddWindow", "Отмена"))
        self.label.setText(_translate("AddWindow", "Введите номер:"))
        self.label_2.setText(_translate("AddWindow", "Введите тел. номер:"))
        self.label_3.setText(_translate("AddWindow", "Введите ФИО:"))
        self.label_4.setText(_translate("AddWindow", "Введите номер квартиры:"))
