# Form implementation generated from reading ui file 'deleteWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteWindow(object):
    def setupUi(self, DeleteWindow):
        DeleteWindow.setObjectName("DeleteWindow")
        DeleteWindow.resize(392, 89)
        self.widget = QtWidgets.QWidget(parent=DeleteWindow)
        self.widget.setGeometry(QtCore.QRect(210, 50, 168, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delBtn = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.delBtn.setFont(font)
        self.delBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.delBtn.setObjectName("delBtn")
        self.horizontalLayout.addWidget(self.delBtn)
        self.cancelBtn = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.widget1 = QtWidgets.QWidget(parent=DeleteWindow)
        self.widget1.setGeometry(QtCore.QRect(11, 11, 372, 29))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.number = QtWidgets.QLineEdit(parent=self.widget1)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.number.setFont(font)
        self.number.setObjectName("number")
        self.horizontalLayout_2.addWidget(self.number)

        self.retranslateUi(DeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteWindow)

    def retranslateUi(self, DeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteWindow.setWindowTitle(_translate("DeleteWindow", "Удалить"))
        self.delBtn.setText(_translate("DeleteWindow", "Удалить"))
        self.cancelBtn.setText(_translate("DeleteWindow", "Отмена"))
        self.label.setText(_translate("DeleteWindow", "Введите номер для удаления: "))
