# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 370)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 521, 321))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_ = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.input_.setFont(font)
        self.input_.setClearButtonEnabled(True)
        self.input_.setObjectName("input_")
        self.horizontalLayout.addWidget(self.input_)
        self.number = QtWidgets.QRadioButton(parent=self.widget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.number.setFont(font)
        self.number.setObjectName("number")
        self.horizontalLayout.addWidget(self.number)
        self.phone = QtWidgets.QRadioButton(parent=self.widget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.phone.setFont(font)
        self.phone.setObjectName("phone")
        self.horizontalLayout.addWidget(self.phone)
        self.flat = QtWidgets.QRadioButton(parent=self.widget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.flat.setFont(font)
        self.flat.setObjectName("flat")
        self.horizontalLayout.addWidget(self.flat)
        self.name = QtWidgets.QRadioButton(parent=self.widget)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.result = QtWidgets.QTextEdit(parent=self.widget)
        self.result.setReadOnly(True)
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 541, 25))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.menubar.setFont(font)
        self.menubar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CarNumbers"))
        self.number.setText(_translate("MainWindow", "Номер"))
        self.phone.setText(_translate("MainWindow", "Тел. номер"))
        self.flat.setText(_translate("MainWindow", "Квартира"))
        self.name.setText(_translate("MainWindow", "ФИО"))
